spring.application.name=POS Retail
server.port=8080

# === MySQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/pos_retail?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# === Thymeleaf ===
spring.thymeleaf.cache=false

# === Session ===
server.servlet.session.timeout=30m

# === Mail (Gmail SMTP) ===
# Para recuperaci\u00c3\u00b3n de contrase\u00c3\u00b1a.
# 1) Activa verificaci\u00c3\u00b3n en dos pasos en tu cuenta Gmail.
# 2) Crea una "contrase\u00c3\u00b1a de aplicaci\u00c3\u00b3n" y p\u00c3\u00a9gala aqu\u00c3\u00ad.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080
